//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLiveWriter.CoreServices {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenLiveWriter.CoreServices.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 The specified path ({0}) is invalid 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_InvalidPath {
            get {
                return ResourceManager.GetString("SiteStorageException.InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The specified RootFile value (&quot;{0}&quot;) is invalid 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_InvalidRootFileName {
            get {
                return ResourceManager.GetString("SiteStorageException.InvalidRootFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error accessing manifest for site at {0} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_ManifestAccessError {
            get {
                return ResourceManager.GetString("SiteStorageException.ManifestAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A RootFile was not specified for the site 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_NoRootFileSpecified {
            get {
                return ResourceManager.GetString("SiteStorageException.NoRootFileSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error accessing path {0} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_PathAccessError {
            get {
                return ResourceManager.GetString("SiteStorageException.PathAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Could not locate the path {0} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_PathNotFound {
            get {
                return ResourceManager.GetString("SiteStorageException.PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A Stream that was written to was not closed prior to attempting to read from it (path = {0}) 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_StreamNotClosed {
            get {
                return ResourceManager.GetString("SiteStorageException.StreamNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error copying site from {0} to {1} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_UnableToCopySite {
            get {
                return ResourceManager.GetString("SiteStorageException.UnableToCopySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to create storage at {0} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_UnableToCreateStorage {
            get {
                return ResourceManager.GetString("SiteStorageException.UnableToCreateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error deleting site at {0} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_UnableToDeleteSite {
            get {
                return ResourceManager.GetString("SiteStorageException.UnableToDeleteSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error moving site from {0} to {1} 的當地語系化字串。
        /// </summary>
        internal static string SiteStorageException_UnableToMoveSite {
            get {
                return ResourceManager.GetString("SiteStorageException.UnableToMoveSite", resourceCulture);
            }
        }
    }
}
